### ISSUE TITLE
Citation doesn't work

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/serverless-chat-langchainjs#89] opened 2024-07-10 21:55 UTC
> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)

```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>
- Deploy app successfully with `azd auth` and `azd up`
- Select a card to receive a response.
- Select citation in response

<img width="881" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/a18e589e-aad1-4819-9ec9-778299166452">

- No document found in separate browser tab.

<img width="493" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/fdd51e52-0104-46a4-92e7-d8a11db27999">

- Storage container doesn't have any files

<img width="868" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/05273213-f8e7-4d9a-acf1-e0e22a42c911">

### Any log messages given by the failure

>

### Expected/desired behavior

>

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions

>

### Mention any other details that might be useful

I need to turn off the shared key in order to be able to use this on an internal sub. I don't think the chat app works if I turn that off. What would have to happen functionally to the app to be able to still work but have shared key turned off? 
<img width="517" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/bfb0430e-fdb5-4ea1-aa4f-509dbe6fe4d0">

> ---
>
> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment] 2024-07-31 15:28
Circling back to this issue:
- The first issue you've seen happens when the upload process did not work. Some time ago, if uploading failed the error was silenced but since this [PR](https://github.com/Azure-Samples/serverless-chat-langchainjs/pull/76) this should not be the case anymore. If `azd up` succeed, then it means upload have succeeded. Could you make sure your code is up-to-date  if you ran into the issue again?

- Regarding the "document not found" issue, it's expected if the document is not part of the PDF documents in the data folder. In this case it made up documents because it seems there's none in the DB, but sometimes when running locally it can get filename in the citation as model is not as smart as OpenAI models. But when deployed to Azure, you should never run into this when documents are uploaded successfully.

- Regarding the storage security, using the new flag for [enhanced security](https://github.com/Azure-Samples/serverless-chat-langchainjs/blob/main/docs/enhance-security.md) will disable local auth/shared keys (and the app will still work as expected)

**Comment by sinedied** [comment] 2024-09-19 16:53
@diberry let me know if you reproduce this again on a deployed version, in the meantime I'll close this issue as I was never able to reproduce it with the latest versions.

**Closed by sinedied** 2024-09-19 16:53 UTC
Labels: bug
